"""Shared constants for subprocess timeouts and sizes."""

TIMEOUT_ADB_VERSION = 3
TIMEOUT_ADB_DEVICES = 3
TIMEOUT_MDNS = 5
TIMEOUT_ADB_CONNECT = 5
TIMEOUT_ADB_PAIR = 10
TIMEOUT_FILE_CHECK = 10
TIMEOUT_APK_INSTALL = 60

BYTES_PER_MB = 1024 * 1024
