/**
 * Gradle script to generate TestConstants.kt from test-settings.json
 *
 * This script dynamically parses test-settings.json and generates a Kotlin object
 * with nested objects matching the JSON structure.
 *
 * Usage: ./gradlew generateTestConstants
 */

tasks.register("generateTestConstants") {
    description = "Generates TestConstants.kt from test-settings.json (dynamically parses all fields)"
    group = "build"

    val testSettingsFile = file("src/androidTest/assets/test-settings.json")
    val outputFile = file("src/androidTest/java/app/otter/domain/usecase/helpers/TestConstants.kt")

    inputs.file(testSettingsFile)
    outputs.file(outputFile)

    doLast {
        // Parse JSON
        val jsonContent = testSettingsFile.readText()
        val json = groovy.json.JsonSlurper().parseText(jsonContent) as Map<*, *>

        // Helper functions
        fun String.toCamelCase(): String {
            return split("_").mapIndexed { index, part ->
                if (index == 0) part else part.replaceFirstChar { it.uppercase() }
            }.joinToString("")
        }

        fun String.toPascalCase(): String {
            return split("_").joinToString("") { it.replaceFirstChar { c -> c.uppercase() } }
        }

        fun generateProperty(key: String, value: Any?, indent: String): String {
            val propName = key.toCamelCase()
            return when (value) {
                is String -> "${indent}const val $propName = \"$value\""
                is Number -> "${indent}const val $propName = $value"
                is Boolean -> "${indent}const val $propName = $value"
                null -> "${indent}val $propName: String? = null"
                is List<*> -> {
                    val items = value.joinToString(", ") { "\"$it\"" }
                    "${indent}val $propName = listOf($items)"
                }
                is Map<*, *> -> {
                    val objName = key.toPascalCase()
                    val properties = value.map { (k, v) ->
                        generateProperty(k as String, v, "$indent    ")
                    }.joinToString("\n")
                    """${indent}object $objName {
$properties
${indent}}"""
                }
                else -> "${indent}// Unsupported type for $propName: ${value::class.simpleName}"
            }
        }

        // Generate nested objects
        val properties = json.map { (key, value) ->
            generateProperty(key as String, value, "    ")
        }.joinToString("\n\n")

        // Generate Kotlin file
        val kotlinCode = """
            |package app.otter.domain.usecase.helpers
            |
            |/**
            | * Global constants for instrumented tests.
            | *
            | * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
            | * Generated from: src/androidTest/assets/test-settings.json
            | * To regenerate: ./gradlew generateTestConstants
            | *
            | * This file is automatically generated from test-settings.json.
            | * Any changes to the JSON structure will be reflected here after rebuild.
            | */
            |object TestConstants {
            |$properties
            |}
            |
        """.trimMargin()

        outputFile.writeText(kotlinCode)
        println("✅ Generated TestConstants.kt from test-settings.json")
    }
}

// Auto-generate before building androidTest
tasks.named("preBuild") {
    dependsOn("generateTestConstants")
}
