package app.otter.domain.usecase.helpers

/**
 * Global constants for instrumented tests.
 *
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: src/androidTest/assets/test-settings.json
 * To regenerate: ./gradlew generateTestConstants
 *
 * This file is automatically generated from test-settings.json.
 * Any changes to the JSON structure will be reflected here after rebuild.
 */
object TestConstants {
    object TestArchives {
        const val devicePath = "/storage/emulated/0/otter-test-archives"
        const val hostPath = "archives"
        val files = listOf("test_archive.zip", "test_archive.rar", "test_archive.rpa", "test_archive.7z", "test_archive.tar", "test_archive.tar.gz")
    }

    object Logging {
        const val enabledInTests = false
        val logFilePath: String? = null
    }

    object TestExecution {
        const val instrumentedTimeoutSeconds = 1200
        const val retryOnFailure = false
    }

    object Adb {
        const val connectionTimeoutSeconds = 60
        const val defaultDeviceSelection = "first"
    }
}
