package app.otter.domain.usecase.helpers

/**
 * Global constants for instrumented tests.
 *
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: src/androidTest/assets/test-settings.json
 * To regenerate: ./gradlew generateTestConstants
 *
 * This file is automatically generated from test-settings.json.
 * Any changes to the JSON structure will be reflected here after rebuild.
 */
object TestConstants {
    object TestArchives {
        const val devicePath = "/storage/emulated/0/otter-test-archives"
        const val hostPath = "archives"
        val files = listOf("test_archive.zip", "test_archive.rar", "test_archive.rpa", "test_archive.7z", "test_archive.tar", "test_archive.tar.gz", "test_archive.tar.bz2", "test_archive.gz", "corrupted_test_archive.zip", "corrupted_test_archive.rar", "corrupted_test_archive.rpa", "corrupted_test_archive.7z", "corrupted_test_archive.tar", "corrupted_test_archive.tar.gz", "corrupted_test_archive.tar.bz2", "corrupted_test_archive.gz", "empty_test_archive.zip", "empty_test_archive.rpa", "empty_test_archive.7z", "empty_test_archive.tar", "empty_test_archive.tar.gz", "empty_test_archive.tar.bz2", "malicious_test_archive.zip", "large_test_archive.zip", "large_test_archive.rar", "large_test_archive.rpa", "large_test_archive.7z", "large_test_archive.tar", "large_test_archive.tar.gz", "large_test_archive.tar.bz2", "large_test_archive.gz", "deep_nested_test_archive.zip", "deep_nested_test_archive.rar", "deep_nested_test_archive.rpa", "deep_nested_test_archive.7z", "deep_nested_test_archive.tar", "deep_nested_test_archive.tar.gz", "deep_nested_test_archive.tar.bz2", "deep_nested_test_archive.gz", "long_filename_test_archive.zip", "long_filename_test_archive.rar", "long_filename_test_archive.rpa", "long_filename_test_archive.7z", "long_filename_test_archive.tar", "long_filename_test_archive.tar.gz", "long_filename_test_archive.tar.bz2", "long_filename_test_archive.gz")
    }

    object Logging {
        const val enabledInTests = false
        val logFilePath: String? = null
    }

    object TestExecution {
        const val instrumentedTimeoutSeconds = 1200
        const val retryOnFailure = false
    }

    object Adb {
        const val connectionTimeoutSeconds = 60
        const val defaultDeviceSelection = "first"
    }
}
