name: PR-CI

on:
  workflow_run:
    workflows: ["Push-CI"]
    types: [completed]

permissions:
  pull-requests: write
  contents: read

concurrency:
  group: pr-ci-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  pr-checks:
    uses: TomasGC/condor/.github/workflows/common-pr-ci.yml@main
    secrets: inherit
    with:
      push-ci-conclusion: ${{ github.event.workflow_run.conclusion }}
      head-branch: ${{ github.event.workflow_run.head_branch }}
      head-sha: ${{ github.event.workflow_run.head_sha }}
