name: Push-CI

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'

concurrency:
  group: push-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  kotlin-pipeline:
    uses: TomasGC/condor/.github/workflows/kotlin-push-ci.yml@main
    secrets: inherit
    with:
      pre-test-command: python scripts/manage.py create
      archives-local-dir: archives/
      device-archives-path: /sdcard/otter-test-archives
      app-name: otter

  python-pipeline:
    uses: TomasGC/condor/.github/workflows/python-push-ci.yml@main
    with:
      skip-on-no-changes: true
